[versions]
bootstrap = "5.3.8"
bootstrapIcons = "1.13.1"
caffeine = "3.2.4"
gitlab4jApi = "6.3.0"
htmx = "2.0.10"
kotest = "6.2.4"
kotlin = "2.4.10"
kotlinLogging = "8.0.4"
mockk = "1.14.11"
mschoutConventions = "0.7.1"
spotless = "8.10.0"
springBoot = "4.1.0"
springDependencyManagement = "1.1.7"
springSecurityWebauthn = "7.1.1"
springdoc = "3.1.0"
testcontainers = "1.21.4"
totp = "1.7.1"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
gitlab4j-api = { module = "org.gitlab4j:gitlab4j-api", version.ref = "gitlab4jApi" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
postgresql = { module = "org.postgresql:postgresql" }
samstevens-totp = { module = "dev.samstevens.totp:totp", version.ref = "totp" }
spring-boot-flyway = { module = "org.springframework.boot:spring-boot-flyway", version.ref = "springBoot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "springBoot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "springBoot" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "springBoot" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient", version.ref = "springBoot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBoot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "springBoot" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-security-webauthn = { module = "org.springframework.security:spring-security-webauthn", version.ref = "springSecurityWebauthn" }
spring-tx = { module = "org.springframework:spring-tx" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
thymeleaf-extras-springsecurity = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6" }
webjars-bootstrap = { module = "org.webjars.npm:bootstrap", version.ref = "bootstrap" }
webjars-bootstrap-icons = { module = "org.webjars.npm:bootstrap-icons", version.ref = "bootstrapIcons" }
webjars-htmx = { module = "org.webjars.npm:htmx.org", version.ref = "htmx" }

[plugins]
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
mschout-conventions = { id = "io.github.mschout.all-conventions", version.ref = "mschoutConventions" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }

[bundles]
kotest = [
    "kotest-assertions-core",
    "kotest-runner-junit5",
]
spring = [
    "spring-boot-starter-cache",
    "spring-boot-starter-data-jpa",
    "spring-boot-starter-oauth2-client",
    "spring-boot-starter-restclient",
    "spring-boot-starter-security",
    "spring-boot-starter-thymeleaf",
    "spring-boot-starter-validation",
    "spring-boot-starter-web",
    "spring-security-webauthn",
    "spring-tx",
]
testcontainers = [
    "spring-boot-testcontainers",
    "testcontainers-junit-jupiter",
    "testcontainers-postgresql",
]
webjars = [
    "webjars-bootstrap",
    "webjars-bootstrap-icons",
    "webjars-htmx",
]
